export const histoireModerneQuestionData = [
    [
        "histoire-026",
        "Que sont les chinampas utilisées autour de Tenochtitlan par les Aztèques ?",
        [
            "Des temples réservés aux marchands",
            "Des routes pavées traversant les montagnes",
            "Des parcelles agricoles aménagées dans les zones peu profondes du lac",
            "Des registres fiscaux écrits sur des cordelettes",
        ],
        2,
        "Les chinampas formaient des surfaces cultivables très productives, aménagées dans le milieu lacustre de la vallée de Mexico.",
    ],
    [
        "histoire-027",
        "À quoi servaient principalement les quipus dans l’Empire inca ?",
        [
            "À imprimer des décrets sur papier",
            "À orienter les navires dans le Pacifique",
            "À enregistrer des informations au moyen de cordelettes nouées",
            "À mesurer le temps avec des ombres solaires",
        ],
        2,
        "Les quipus permettaient notamment de conserver des données numériques utiles à l’administration, aux recensements et aux prélèvements.",
    ],
    [
        "histoire-028",
        "Sous quelle dynastie chinoise l’amiral Zheng He mena-t-il ses grandes expéditions maritimes ?",
        [
            "La dynastie Tang",
            "La dynastie Ming",
            "La dynastie Song",
            "La dynastie Qing",
        ],
        1,
        "Au début du XVe siècle, Zheng He commanda des flottes Ming vers l’Asie du Sud-Est, l’Inde, l’Arabie et les côtes de l’Afrique orientale.",
    ],
    [
        "histoire-029",
        "Quel souverain ottoman conquit Constantinople en 1453 ?",
        [
            "Soliman le Magnifique",
            "Mehmed II",
            "Bayezid Ier",
            "Sélim Ier",
        ],
        1,
        "La prise de Constantinople par Mehmed II mit fin à l’Empire byzantin et renforça la puissance ottomane en Méditerranée orientale.",
    ],
    [
        "histoire-030",
        "Quel fut l’un des principaux effets de l’imprimerie à caractères mobiles perfectionnée par Gutenberg en Europe ?",
        [
            "La disparition immédiate des manuscrits",
            "L’invention de l’écriture alphabétique",
            "L’interdiction des traductions religieuses",
            "La production plus rapide et moins coûteuse de nombreux livres",
        ],
        3,
        "L’imprimerie facilita la diffusion des textes, des idées religieuses et savantes, ainsi que l’élargissement progressif du lectorat.",
    ],
    [
        "histoire-031",
        "Pourquoi le voyage de Vasco de Gama achevé en 1498 fut-il important pour le Portugal ?",
        [
            "Il établit la première route terrestre vers la Chine",
            "Il permit la conquête immédiate de l’Empire aztèque",
            "Il découvrit le passage du Nord-Ouest",
            "Il ouvrit une route maritime européenne vers l’Inde en contournant l’Afrique",
        ],
        3,
        "En atteignant Calicut par le cap de Bonne-Espérance, l’expédition renforça l’accès portugais au commerce de l’océan Indien.",
    ],
    [
        "histoire-032",
        "Quelle pratique Martin Luther critiquait-il notamment au début de la Réforme protestante ?",
        [
            "Le baptême chrétien",
            "La traduction de la Bible",
            "La vente d’indulgences",
            "L’usage de l’imprimerie",
        ],
        2,
        "Les critiques de Luther contre les indulgences s’inscrivirent dans un débat plus large sur l’autorité religieuse, le salut et les pratiques de l’Église.",
    ],
    [
        "histoire-033",
        "Quelle politique est souvent associée à l’empereur moghol Akbar ?",
        [
            "L’expulsion de tous les non-musulmans de l’empire",
            "La fermeture complète des échanges avec l’Asie centrale",
            "Une recherche d’intégration impériale et de tolérance entre communautés religieuses",
            "Le transfert de la capitale moghole à Pékin",
        ],
        2,
        "Akbar associa des élites diverses à son administration et encouragea le dialogue religieux afin de consolider un empire très pluraliste.",
    ],
    [
        "histoire-034",
        "Quel était l’objectif du système japonais du sankin-kōtai sous les Tokugawa ?",
        [
            "Élire le shogun au suffrage des paysans",
            "Organiser des voyages commerciaux annuels vers l’Amérique",
            "Remplacer les domaines féodaux par des colonies européennes",
            "Contrôler les daimyos en leur imposant une résidence alternée à Edo",
        ],
        3,
        "La résidence alternée obligeait les seigneurs à partager leur temps entre leur domaine et Edo, limitant leurs ressources et renforçant le shogunat.",
    ],
    [
        "histoire-035",
        "Que désigne l’expression « passage du Milieu » dans l’histoire de la traite atlantique ?",
        [
            "La route terrestre entre l’Inde et la Chine",
            "La traversée forcée de l’Atlantique imposée aux Africains réduits en esclavage",
            "Le voyage des colons européens vers l’Australie",
            "Le déplacement des armées ottomanes vers les Balkans",
        ],
        1,
        "Le passage du Milieu fut une étape meurtrière de la traite transatlantique, dans des navires où les captifs subissaient violence, maladie et mortalité élevée.",
    ],
    [
        "histoire-036",
        "Que proclame principalement la Déclaration d’indépendance américaine du 4 juillet 1776 ?",
        [
            "L’abolition immédiate de l’esclavage dans toutes les colonies",
            "L’union politique avec la France",
            "La création de la Société des Nations",
            "La séparation des treize colonies d’avec la Grande-Bretagne",
        ],
        3,
        "La Déclaration justifia la rupture avec la Couronne britannique au nom de droits naturels et de griefs contre le gouvernement royal.",
    ],
    [
        "histoire-037",
        "Quel résultat majeur découla de la révolution haïtienne ?",
        [
            "Le retour durable de Saint-Domingue sous domination espagnole",
            "La création d’une monarchie française en Amérique",
            "L’annexion d’Haïti par les États-Unis",
            "L’abolition de l’esclavage dans la colonie et l’indépendance d’Haïti en 1804",
        ],
        3,
        "La révolution menée par d’anciens esclaves renversa l’ordre colonial de Saint-Domingue et donna naissance au premier État indépendant issu d’une révolte servile victorieuse.",
    ],
    [
        "histoire-038",
        "Quel principe figure dans la Déclaration des droits de l’homme et du citoyen de 1789 ?",
        [
            "L’égalité des citoyens devant la loi",
            "Le pouvoir absolu du monarque",
            "Le maintien des privilèges juridiques de naissance",
            "L’interdiction de toute représentation nationale",
        ],
        0,
        "Le texte affirma des droits naturels et l’égalité juridique, même si leur application resta alors incomplète pour les femmes, les esclaves et d’autres groupes.",
    ],
    [
        "histoire-039",
        "Quelle combinaison joua un rôle central dans la première révolution industrielle en Grande-Bretagne ?",
        [
            "L’électricité nucléaire, l’aluminium et l’aviation",
            "La poudre à canon, la soie et les galères",
            "La mécanisation du textile, le charbon et la machine à vapeur",
            "Le pétrole, l’automobile et l’informatique",
        ],
        2,
        "À partir du XVIIIe siècle, le textile mécanisé, l’énergie du charbon et la vapeur transformèrent la production, les transports et l’organisation du travail.",
    ],
    [
        "histoire-040",
        "Dans quelles régions Simón Bolívar joua-t-il un rôle majeur dans les indépendances du début du XIXe siècle ?",
        [
            "Dans les colonies britanniques d’Amérique du Nord",
            "Dans les Balkans ottomans",
            "Dans le nord de l’Amérique du Sud",
            "Dans l’Asie du Sud-Est néerlandaise",
        ],
        2,
        "Bolívar participa aux indépendances de territoires correspondant notamment au Venezuela, à la Colombie, à l’Équateur, au Pérou et à la Bolivie.",
    ],
    [
        "histoire-041",
        "Quelle transformation politique caractérise la restauration de Meiji au Japon à partir de 1868 ?",
        [
            "Le renforcement d’un État impérial centralisé engagé dans la modernisation",
            "Le retour à une confédération de clans totalement autonomes",
            "La colonisation immédiate du Japon par la Russie",
            "L’abolition de toute armée nationale",
        ],
        0,
        "La restauration de Meiji mit fin au shogunat Tokugawa et lança des réformes administratives, militaires, éducatives et industrielles rapides.",
    ],
    [
        "histoire-042",
        "Quel fut l’un des principaux objectifs de la conférence de Berlin de 1884-1885 ?",
        [
            "Organiser l’indépendance immédiate de toutes les colonies africaines",
            "Créer une fédération politique africaine",
            "Fixer des règles entre puissances européennes pour leurs revendications coloniales en Afrique",
            "Mettre fin au commerce européen sur le continent",
        ],
        2,
        "La conférence établit notamment le principe d’occupation effective, accélérant la compétition impériale sans représentation des sociétés africaines concernées.",
    ],
    [
        "histoire-043",
        "Quel événement déclencha immédiatement la crise européenne menant à la Première Guerre mondiale ?",
        [
            "L’assassinat de l’archiduc François-Ferdinand à Sarajevo",
            "La chute de la Bourse de New York",
            "La révolution russe de Février",
            "L’invasion de la Pologne par l’Allemagne",
        ],
        0,
        "L’attentat du 28 juin 1914 provoqua un enchaînement d’ultimatums et de mobilisations dans un contexte déjà tendu par les alliances et les rivalités impériales.",
    ],
    [
        "histoire-044",
        "Que firent les bolcheviks lors de la révolution d’Octobre 1917 en Russie ?",
        [
            "Ils renversèrent le gouvernement provisoire et prirent le pouvoir à Petrograd",
            "Ils restaurèrent le tsar Nicolas II",
            "Ils proclamèrent l’indépendance des États-Unis",
            "Ils signèrent le traité de Versailles",
        ],
        0,
        "Dirigés par Lénine, les bolcheviks s’emparèrent des principaux centres de pouvoir et engagèrent la Russie dans une transformation révolutionnaire et une guerre civile.",
    ],
    [
        "histoire-045",
        "Quelle conséquence mondiale caractérisa la Grande Dépression des années 1930 ?",
        [
            "Une croissance industrielle continue dans tous les pays",
            "Une forte hausse du chômage et une contraction du commerce international",
            "La disparition des politiques protectionnistes",
            "L’instauration immédiate d’une monnaie mondiale unique",
        ],
        1,
        "La crise bancaire et financière, combinée à l’effondrement de la demande et aux barrières commerciales, provoqua une dépression économique durable dans de nombreux pays.",
    ],
    [
        "histoire-046",
        "Quel était l’objectif principal du débarquement allié en Normandie le 6 juin 1944 ?",
        [
            "Envahir l’Union soviétique",
            "Ouvrir un front majeur en Europe occidentale contre l’Allemagne nazie",
            "Défendre l’Italie contre les Alliés",
            "Mettre fin à la guerre du Pacifique",
        ],
        1,
        "L’opération Overlord établit une tête de pont en France occupée et contribua à la libération de l’Europe occidentale.",
    ],
    [
        "histoire-047",
        "Quelle conséquence territoriale accompagna l’indépendance de l’Inde britannique en 1947 ?",
        [
            "L’annexion de l’Inde par la Chine",
            "La partition en deux États, l’Inde et le Pakistan",
            "La réunification avec la Birmanie",
            "La création immédiate du Bangladesh comme troisième État",
        ],
        1,
        "La partition selon des lignes principalement religieuses provoqua d’immenses déplacements de population et de graves violences entre communautés.",
    ],
    [
        "histoire-048",
        "Pourquoi la crise des missiles de Cuba de 1962 fut-elle un moment particulièrement dangereux de la guerre froide ?",
        [
            "Elle opposa directement les États-Unis et l’URSS autour de missiles nucléaires soviétiques installés à Cuba",
            "Elle déclencha une guerre conventionnelle entre la Chine et le Japon",
            "Elle provoqua l’invasion de Cuba par l’Espagne",
            "Elle entraîna la dissolution immédiate de l’OTAN",
        ],
        0,
        "Pendant treize jours, le risque d’escalade nucléaire fut très élevé avant un accord prévoyant notamment le retrait des missiles soviétiques de Cuba.",
    ],
    [
        "histoire-049",
        "Quelle organisation économique le traité de Rome de 1957 créa-t-il ?",
        [
            "La Communauté économique européenne",
            "La Société des Nations",
            "Le Conseil de l’Europe",
            "L’Organisation du traité de l’Atlantique nord",
        ],
        0,
        "Signé par six États, le traité de Rome fonda la CEE, étape majeure de l’intégration économique qui conduira ensuite à l’Union européenne.",
    ],
    [
        "histoire-050",
        "Que marquèrent les élections sud-africaines d’avril 1994 ?",
        [
            "Le début officiel de l’apartheid",
            "L’indépendance de l’Afrique du Sud vis-à-vis du Portugal",
            "La création de l’Organisation de l’unité africaine",
            "Les premières élections nationales multiraciales et l’arrivée de Nelson Mandela à la présidence",
        ],
        3,
        "Ces élections concrétisèrent la transition négociée hors de l’apartheid et portèrent au pouvoir un gouvernement issu du suffrage de l’ensemble de la population adulte.",
    ],
] as const;
