export const histoireAncienneQuestionData = [
    [
        "histoire-001",
        "À quelle période préhistorique appartiennent principalement les peintures de la grotte de Lascaux ?",
        [
            "Au Néolithique",
            "Au Paléolithique supérieur",
            "À l’âge du bronze",
            "À l’Antiquité romaine",
        ],
        1,
        "Les peintures de Lascaux ont été réalisées au Paléolithique supérieur, il y a environ 17 000 ans, par des groupes de chasseurs-cueilleurs.",
    ],
    [
        "histoire-002",
        "Quelle transformation caractérise le mieux la révolution néolithique ?",
        [
            "L’invention de l’écriture alphabétique",
            "Le développement de l’agriculture et de l’élevage",
            "La généralisation de la métallurgie du fer",
            "L’usage de la machine à vapeur",
        ],
        1,
        "La révolution néolithique correspond au passage progressif de nombreuses sociétés vers la production de nourriture, la sédentarisation et l’élevage.",
    ],
    [
        "histoire-003",
        "Quel système d’écriture est associé aux cités sumériennes de Mésopotamie ?",
        [
            "Les hiéroglyphes égyptiens",
            "L’écriture cunéiforme",
            "L’alphabet latin",
            "Les quipus",
        ],
        1,
        "L’écriture cunéiforme, tracée sur des tablettes d’argile, apparaît en Mésopotamie à la fin du IVe millénaire avant notre ère.",
    ],
    [
        "histoire-004",
        "Pourquoi les crues annuelles du Nil étaient-elles essentielles à l’Égypte antique ?",
        [
            "Elles déposaient un limon fertile sur les terres cultivées",
            "Elles alimentaient directement les mines de cuivre du Sinaï",
            "Elles empêchaient toute navigation vers la Méditerranée",
            "Elles provoquaient la disparition annuelle des villages",
        ],
        0,
        "Les crues du Nil enrichissaient les sols en limon et soutenaient une agriculture productive dans un environnement largement désertique.",
    ],
    [
        "histoire-005",
        "Hammurabi, connu pour le recueil de lois qui porte son nom, régnait sur quelle cité ?",
        [
            "Babylone",
            "Ur",
            "Ninive",
            "Suse",
        ],
        0,
        "Hammurabi fut roi de Babylone au XVIIIe siècle avant notre ère et fit graver un célèbre ensemble de décisions juridiques.",
    ],
    [
        "histoire-006",
        "Mohenjo-Daro était l’une des grandes villes de quelle civilisation ancienne ?",
        [
            "La civilisation minoenne",
            "La civilisation olmèque",
            "La civilisation hittite",
            "La civilisation de l’Indus",
        ],
        3,
        "Mohenjo-Daro, dans l’actuel Pakistan, appartenait à la civilisation de l’Indus, remarquable notamment par son urbanisme et ses réseaux d’évacuation.",
    ],
    [
        "histoire-007",
        "À quoi servaient principalement les os oraculaires sous la dynastie Shang en Chine ?",
        [
            "À enregistrer les impôts provinciaux",
            "À former les soldats au tir à l’arc",
            "À pratiquer la divination pour la cour royale",
            "À frapper les premières monnaies chinoises",
        ],
        2,
        "Des questions étaient inscrites sur des omoplates ou des carapaces, puis chauffées afin d’interpréter les fissures comme des présages.",
    ],
    [
        "histoire-008",
        "Quelle contribution des Phéniciens a fortement influencé les systèmes d’écriture méditerranéens ?",
        [
            "La diffusion d’un alphabet consonantique",
            "L’invention du papier",
            "La création des chiffres romains",
            "La mise au point de l’imprimerie à caractères mobiles",
        ],
        0,
        "L’alphabet phénicien, adapté ensuite par les Grecs, a contribué à la formation de plusieurs alphabets utilisés autour de la Méditerranée.",
    ],
    [
        "histoire-009",
        "Dans l’Athènes classique, qui pouvait normalement participer à l’Assemblée des citoyens ?",
        [
            "Tous les habitants libres de l’Attique",
            "Les femmes nées de parents athéniens",
            "Les hommes adultes reconnus comme citoyens athéniens",
            "Les esclaves affranchis installés dans la cité",
        ],
        2,
        "La démocratie athénienne était directe, mais la citoyenneté politique excluait notamment les femmes, les esclaves et les étrangers résidents.",
    ],
    [
        "histoire-010",
        "La Route royale facilitait les communications au sein de quel empire antique ?",
        [
            "L’Empire maurya",
            "L’Empire perse achéménide",
            "L’Empire carthaginois",
            "L’Empire inca",
        ],
        1,
        "La Route royale reliait notamment Suse à Sardes et permettait aux souverains achéménides de transmettre rapidement des messages dans leur vaste empire.",
    ],
    [
        "histoire-011",
        "Quel phénomène culturel accompagna les conquêtes d’Alexandre le Grand ?",
        [
            "La disparition immédiate des langues locales",
            "L’unification religieuse autour du judaïsme",
            "La diffusion de la culture grecque et son mélange avec des traditions locales",
            "L’abandon du commerce méditerranéen",
        ],
        2,
        "Les conquêtes d’Alexandre ouvrirent la période hellénistique, marquée par des échanges entre traditions grecques, égyptiennes, perses et asiatiques.",
    ],
    [
        "histoire-012",
        "Quel changement est associé au règne de l’empereur maurya Ashoka après la guerre de Kalinga ?",
        [
            "La conversion de l’empire au christianisme",
            "La promotion du bouddhisme et d’une politique de non-violence",
            "L’abolition de toutes les administrations provinciales",
            "La conquête militaire de la Chine des Han",
        ],
        1,
        "Après la guerre de Kalinga, Ashoka soutint le bouddhisme et fit graver des édits valorisant la modération, la compassion et le respect des sujets.",
    ],
    [
        "histoire-013",
        "Quelle mesure de la dynastie Qin renforça l’unification de la Chine au IIIe siècle avant notre ère ?",
        [
            "La standardisation des poids, des mesures et de l’écriture",
            "La suppression de toute monnaie",
            "L’adoption du grec comme langue administrative",
            "La division durable du territoire en royaumes indépendants",
        ],
        0,
        "Les Qin harmonisèrent plusieurs normes administratives et matérielles, ce qui facilita le contrôle et les échanges dans l’empire unifié.",
    ],
    [
        "histoire-014",
        "Sous la République romaine, quel était le rôle des consuls ?",
        [
            "Ils étaient deux magistrats supérieurs élus pour diriger l’État et les armées",
            "Ils étaient des prêtres chargés uniquement du calendrier",
            "Ils gouvernaient à vie comme des rois héréditaires",
            "Ils représentaient exclusivement les provinces conquises",
        ],
        0,
        "Deux consuls élus chaque année exerçaient la plus haute magistrature ordinaire, un partage du pouvoir destiné à limiter la concentration de l’autorité.",
    ],
    [
        "histoire-015",
        "Pourquoi le royaume d’Aksoum occupait-il une position commerciale importante dans l’Antiquité tardive ?",
        [
            "Il dominait les passages terrestres à travers les Alpes",
            "Il possédait le monopole du commerce de la Baltique",
            "Il contrôlait directement la route maritime vers le Japon",
            "Il contrôlait des routes reliant la mer Rouge, l’Afrique intérieure et l’océan Indien",
        ],
        3,
        "Situé dans les actuelles Éthiopie et Érythrée, Aksoum profita des échanges entre le monde méditerranéen, l’Afrique et l’océan Indien.",
    ],
    [
        "histoire-016",
        "Quel rôle les routes de la soie jouèrent-elles sous la dynastie Han ?",
        [
            "Elles isolèrent la Chine de tout commerce extérieur",
            "Elles servirent uniquement au transport de soldats vers la Corée",
            "Elles relièrent directement Pékin à l’Amérique",
            "Elles favorisèrent les échanges entre la Chine, l’Asie centrale et des régions plus occidentales",
        ],
        3,
        "Ces réseaux terrestres et maritimes firent circuler des marchandises, des techniques, des croyances et des informations sur de longues distances.",
    ],
    [
        "histoire-017",
        "Quelle caractéristique distingue particulièrement la civilisation maya classique ?",
        [
            "Un système d’écriture glyphique élaboré et des calendriers complexes",
            "L’usage généralisé du fer pour les armes",
            "La construction de routes pavées reliant tout le continent",
            "L’adoption de l’alphabet latin avant l’arrivée des Européens",
        ],
        0,
        "Les Mayas développèrent une écriture logosyllabique et des systèmes calendaires précis, utilisés dans des cités-États de Mésoamérique.",
    ],
    [
        "histoire-018",
        "Que désigne le Corpus Juris Civilis compilé sous l’empereur byzantin Justinien ?",
        [
            "Un manuel de stratégie navale",
            "Une vaste compilation du droit romain",
            "Un recueil de chants liturgiques slaves",
            "Un traité commercial avec la Chine",
        ],
        1,
        "La compilation justinienne rassembla et réorganisa le droit romain ; elle influença durablement les traditions juridiques européennes.",
    ],
    [
        "histoire-019",
        "Dans l’histoire de l’islam, que commémore l’Hégire de 622 ?",
        [
            "La conquête de Constantinople",
            "La fondation de Bagdad",
            "Le départ de Mahomet et de ses compagnons de La Mecque vers Médine",
            "La fin du califat omeyyade en Espagne",
        ],
        2,
        "L’Hégire marque la formation d’une communauté musulmane à Médine et sert de point de départ au calendrier musulman.",
    ],
    [
        "histoire-020",
        "Quelle activité est particulièrement associée à la Maison de la sagesse de Bagdad sous les Abbassides ?",
        [
            "La traduction et l’étude de textes scientifiques et philosophiques",
            "La formation exclusive de cavaliers militaires",
            "La fabrication des mosaïques de Sainte-Sophie",
            "La collecte des impôts de l’Empire byzantin",
        ],
        0,
        "Bagdad fut un grand centre intellectuel où des savants travaillèrent sur des œuvres grecques, persanes et indiennes, tout en produisant de nouvelles recherches.",
    ],
    [
        "histoire-021",
        "Pourquoi le pèlerinage de Mansa Musa à La Mecque en 1324 est-il resté célèbre ?",
        [
            "Il marqua la conversion de l’Empire du Mali au christianisme",
            "Il déclencha la conquête du Maghreb par le Mali",
            "Il mit fin au commerce transsaharien",
            "Il manifesta la richesse en or et le prestige de l’Empire du Mali",
        ],
        3,
        "Le souverain malien voyagea avec une suite imposante et distribua beaucoup d’or, révélant aux observateurs la puissance économique de son empire.",
    ],
    [
        "histoire-022",
        "Sur quoi reposait en partie la prospérité du Grand Zimbabwe entre les XIe et XVe siècles ?",
        [
            "La production de soie destinée à la Chine",
            "Le commerce de l’or et du bétail avec les réseaux de l’océan Indien",
            "Le contrôle des mines d’argent du Mexique",
            "La taxation des navires traversant le détroit de Gibraltar",
        ],
        1,
        "Le Grand Zimbabwe était relié aux ports de la côte swahilie et participa à des échanges de l’intérieur africain vers l’océan Indien.",
    ],
    [
        "histoire-023",
        "Comment les navigateurs polynésiens pouvaient-ils parcourir de longues distances dans le Pacifique avant les instruments modernes ?",
        [
            "En suivant des voies ferrées entre les îles",
            "En utilisant des cartes imprimées en Europe",
            "En observant les étoiles, les houles, les vents et les oiseaux",
            "En se guidant uniquement avec des boussoles magnétiques chinoises",
        ],
        2,
        "Les savoirs de navigation polynésiens combinaient de nombreux indices naturels et une transmission orale précise des routes océaniques.",
    ],
    [
        "histoire-024",
        "Quel effet la « Pax Mongolica » eut-elle au XIIIe siècle ?",
        [
            "Elle interdit le commerce entre l’Europe et l’Asie",
            "Elle supprima toutes les frontières maritimes de l’océan Indien",
            "Elle mit fin aux rivalités entre les dynasties chinoises pendant cinq siècles",
            "Elle facilita temporairement les échanges et les déplacements à travers une grande partie de l’Eurasie",
        ],
        3,
        "L’unification mongole de vastes territoires sécurisa certaines routes et favorisa la circulation de marchands, d’ambassadeurs, de techniques et de maladies.",
    ],
    [
        "histoire-025",
        "Quelle idée politique la Magna Carta de 1215 contribua-t-elle à affirmer en Angleterre ?",
        [
            "Le suffrage universel immédiat",
            "L’abolition complète de la noblesse",
            "L’indépendance des colonies anglaises d’Amérique",
            "Le roi devait lui aussi respecter certaines règles juridiques",
        ],
        3,
        "Accord imposé au roi Jean par des barons, la Magna Carta limita certains abus royaux et devint plus tard un symbole de gouvernement soumis au droit.",
    ],
] as const;
