import type { QuestionCategory } from "./types";

export const sciencesCategory: QuestionCategory = {
    id: "category-sciences",
    slug: "sciences",
    title: "Sciences",
    description: "Explorez le vivant, la matière, l’Univers et les grandes découvertes scientifiques.",
    questions: [
        {
            id: "sciences-001",
            prompt: "Quel organite cellulaire produit l’essentiel de l’ATP utilisé par une cellule animale ?",
            options: [
                { id: "sciences-001-a", label: "La mitochondrie" },
                { id: "sciences-001-b", label: "L’appareil de Golgi" },
                { id: "sciences-001-c", label: "Le lysosome" },
                { id: "sciences-001-d", label: "Le ribosome" },
            ],
            correctOptionId: "sciences-001-a",
            explanation: "La mitochondrie réalise la respiration cellulaire, qui convertit l’énergie des nutriments en ATP utilisable par la cellule.",
        },
        {
            id: "sciences-002",
            prompt: "Quelle molécule porte principalement l’information génétique chez les êtres vivants ?",
            options: [
                { id: "sciences-002-a", label: "L’ADN" },
                { id: "sciences-002-b", label: "Le cholestérol" },
                { id: "sciences-002-c", label: "Le glycogène" },
                { id: "sciences-002-d", label: "L’ATP" },
            ],
            correctOptionId: "sciences-002-a",
            explanation: "L’ADN contient des séquences de nucléotides qui constituent les gènes et transmettent l’information héréditaire.",
        },
        {
            id: "sciences-003",
            prompt: "Quel gaz une plante absorbe-t-elle principalement pendant la photosynthèse ?",
            options: [
                { id: "sciences-003-a", label: "Le dioxygène" },
                { id: "sciences-003-b", label: "L’ozone" },
                { id: "sciences-003-c", label: "Le diazote" },
                { id: "sciences-003-d", label: "Le dioxyde de carbone" },
            ],
            correctOptionId: "sciences-003-d",
            explanation: "La plante utilise le dioxyde de carbone avec l’eau et l’énergie lumineuse pour fabriquer de la matière organique.",
        },
        {
            id: "sciences-004",
            prompt: "Quel est le plus grand organe du corps humain ?",
            options: [
                { id: "sciences-004-a", label: "L’intestin grêle" },
                { id: "sciences-004-b", label: "Le foie" },
                { id: "sciences-004-c", label: "Le poumon" },
                { id: "sciences-004-d", label: "La peau" },
            ],
            correctOptionId: "sciences-004-d",
            explanation: "La peau recouvre tout le corps et constitue l’organe le plus étendu, jouant notamment un rôle de protection et de thermorégulation.",
        },
        {
            id: "sciences-005",
            prompt: "Quelles cellules sanguines transportent principalement le dioxygène ?",
            options: [
                { id: "sciences-005-a", label: "Les plaquettes" },
                { id: "sciences-005-b", label: "Les lymphocytes" },
                { id: "sciences-005-c", label: "Les globules rouges" },
                { id: "sciences-005-d", label: "Les macrophages" },
            ],
            correctOptionId: "sciences-005-c",
            explanation: "Les globules rouges contiennent de l’hémoglobine, une protéine qui fixe le dioxygène dans les poumons et le délivre aux tissus.",
        },
        {
            id: "sciences-006",
            prompt: "Dans une synapse chimique, quel type de substance transmet le signal d’un neurone à l’autre ?",
            options: [
                { id: "sciences-006-a", label: "Un neurotransmetteur" },
                { id: "sciences-006-b", label: "Une enzyme digestive" },
                { id: "sciences-006-c", label: "Un anticorps" },
                { id: "sciences-006-d", label: "Une hormone thyroïdienne" },
            ],
            correctOptionId: "sciences-006-a",
            explanation: "Le neurone présynaptique libère un neurotransmetteur, qui se fixe sur des récepteurs de la cellule postsynaptique.",
        },
        {
            id: "sciences-007",
            prompt: "Combien d’os compte habituellement le squelette humain adulte ?",
            options: [
                { id: "sciences-007-a", label: "206" },
                { id: "sciences-007-b", label: "106" },
                { id: "sciences-007-c", label: "306" },
                { id: "sciences-007-d", label: "406" },
            ],
            correctOptionId: "sciences-007-a",
            explanation: "Le squelette adulte compte généralement 206 os ; plusieurs os présents à la naissance fusionnent pendant la croissance.",
        },
        {
            id: "sciences-008",
            prompt: "Quel groupe rassemble les seuls mammifères capables d’un vol actif et soutenu ?",
            options: [
                { id: "sciences-008-a", label: "Les chauves-souris" },
                { id: "sciences-008-b", label: "Les écureuils volants" },
                { id: "sciences-008-c", label: "Les colugos" },
                { id: "sciences-008-d", label: "Les phalangers volants" },
            ],
            correctOptionId: "sciences-008-a",
            explanation: "Les chauves-souris battent réellement des ailes pour voler, tandis que les autres mammifères cités ne font que planer.",
        },
        {
            id: "sciences-009",
            prompt: "Combien de cœurs possède une pieuvre ?",
            options: [
                { id: "sciences-009-a", label: "Deux" },
                { id: "sciences-009-b", label: "Quatre" },
                { id: "sciences-009-c", label: "Trois" },
                { id: "sciences-009-d", label: "Un" },
            ],
            correctOptionId: "sciences-009-c",
            explanation: "Deux cœurs envoient le sang vers les branchies et un troisième le distribue au reste du corps.",
        },
        {
            id: "sciences-010",
            prompt: "Au cours de la métamorphose de la grenouille, quel stade précède l’adulte ?",
            options: [
                { id: "sciences-010-a", label: "La nymphe" },
                { id: "sciences-010-b", label: "La chrysalide" },
                { id: "sciences-010-c", label: "Le têtard" },
                { id: "sciences-010-d", label: "La larve apode" },
            ],
            correctOptionId: "sciences-010-c",
            explanation: "Le têtard est la larve aquatique de la grenouille ; il développe ensuite des membres et perd progressivement sa queue.",
        },
        {
            id: "sciences-011",
            prompt: "Quel tissu végétal transporte surtout l’eau et les sels minéraux des racines vers les parties aériennes ?",
            options: [
                { id: "sciences-011-a", label: "Le cambium" },
                { id: "sciences-011-b", label: "Le xylème" },
                { id: "sciences-011-c", label: "L’épiderme" },
                { id: "sciences-011-d", label: "Le phloème" },
            ],
            correctOptionId: "sciences-011-b",
            explanation: "Le xylème conduit la sève brute, composée principalement d’eau et de sels minéraux absorbés par les racines.",
        },
        {
            id: "sciences-012",
            prompt: "Quel est le rôle principal des stomates présents à la surface des feuilles ?",
            options: [
                { id: "sciences-012-a", label: "Fixer la feuille à la tige" },
                { id: "sciences-012-b", label: "Réguler les échanges gazeux et la perte d’eau" },
                { id: "sciences-012-c", label: "Transporter la sève élaborée" },
                { id: "sciences-012-d", label: "Produire directement les graines" },
            ],
            correctOptionId: "sciences-012-b",
            explanation: "L’ouverture des stomates permet l’entrée du dioxyde de carbone, mais entraîne aussi une perte d’eau par transpiration.",
        },
        {
            id: "sciences-013",
            prompt: "Dans quelle structure des cellules végétales se déroule la photosynthèse ?",
            options: [
                { id: "sciences-013-a", label: "Le chloroplaste" },
                { id: "sciences-013-b", label: "Le noyau" },
                { id: "sciences-013-c", label: "La mitochondrie" },
                { id: "sciences-013-d", label: "Le ribosome" },
            ],
            correctOptionId: "sciences-013-a",
            explanation: "Les chloroplastes contiennent notamment la chlorophylle, qui capte l’énergie lumineuse nécessaire à la photosynthèse.",
        },
        {
            id: "sciences-014",
            prompt: "Quel gaz contribue le plus au réchauffement climatique d’origine humaine par ses émissions cumulées ?",
            options: [
                { id: "sciences-014-a", label: "Le protoxyde d’azote" },
                { id: "sciences-014-b", label: "Le méthane" },
                { id: "sciences-014-c", label: "Le dioxyde de carbone" },
                { id: "sciences-014-d", label: "L’hexafluorure de soufre" },
            ],
            correctOptionId: "sciences-014-c",
            explanation: "D’autres gaz ont un pouvoir réchauffant plus élevé par molécule, mais le dioxyde de carbone domine l’effet cumulé des activités humaines.",
        },
        {
            id: "sciences-015",
            prompt: "Pourquoi les pollinisateurs sont-ils essentiels à de nombreuses plantes à fleurs ?",
            options: [
                { id: "sciences-015-a", label: "Ils empêchent toute prédation des graines" },
                { id: "sciences-015-b", label: "Ils fabriquent la chlorophylle" },
                {
                    id: "sciences-015-c",
                    label: "Ils transportent le pollen entre les organes reproducteurs",
                },
                { id: "sciences-015-d", label: "Ils enrichissent directement le sol en azote" },
            ],
            correctOptionId: "sciences-015-c",
            explanation: "En déplaçant le pollen, les pollinisateurs favorisent la fécondation et donc la formation de graines et souvent de fruits.",
        },
        {
            id: "sciences-016",
            prompt: "Quelle est l’unité de la force dans le Système international ?",
            options: [
                { id: "sciences-016-a", label: "Le joule" },
                { id: "sciences-016-b", label: "Le watt" },
                { id: "sciences-016-c", label: "Le newton" },
                { id: "sciences-016-d", label: "Le pascal" },
            ],
            correctOptionId: "sciences-016-c",
            explanation: "Le newton mesure une force ; un newton accélère une masse d’un kilogramme de un mètre par seconde carrée.",
        },
        {
            id: "sciences-017",
            prompt: "Quelle valeur approche le mieux l’accélération de la pesanteur à la surface de la Terre ?",
            options: [
                { id: "sciences-017-a", label: "24,8 m/s²" },
                { id: "sciences-017-b", label: "3,71 m/s²" },
                { id: "sciences-017-c", label: "9,81 m/s²" },
                { id: "sciences-017-d", label: "1,62 m/s²" },
            ],
            correctOptionId: "sciences-017-c",
            explanation: "Près de la surface terrestre, l’accélération gravitationnelle moyenne vaut environ 9,81 mètres par seconde carrée.",
        },
        {
            id: "sciences-018",
            prompt: "Quel principe explique qu’un objet conserve son état de repos ou de mouvement rectiligne uniforme si la résultante des forces est nulle ?",
            options: [
                { id: "sciences-018-a", label: "L’effet Doppler" },
                { id: "sciences-018-b", label: "La loi de Hooke" },
                { id: "sciences-018-c", label: "Le principe d’Archimède" },
                { id: "sciences-018-d", label: "Le principe d’inertie" },
            ],
            correctOptionId: "sciences-018-d",
            explanation: "Le principe d’inertie, associé à la première loi de Newton, décrit le mouvement d’un corps lorsqu’aucune force résultante ne s’exerce sur lui.",
        },
        {
            id: "sciences-019",
            prompt: "Si la vitesse d’un objet double sans changement de masse, par quel facteur son énergie cinétique est-elle multipliée ?",
            options: [
                { id: "sciences-019-a", label: "Par quatre" },
                { id: "sciences-019-b", label: "Par deux" },
                { id: "sciences-019-c", label: "Par trois" },
                { id: "sciences-019-d", label: "Par huit" },
            ],
            correctOptionId: "sciences-019-a",
            explanation: "L’énergie cinétique est proportionnelle au carré de la vitesse ; doubler la vitesse multiplie donc cette énergie par quatre.",
        },
        {
            id: "sciences-020",
            prompt: "Quelle est l’unité de la pression dans le Système international ?",
            options: [
                { id: "sciences-020-a", label: "Le tesla" },
                { id: "sciences-020-b", label: "Le pascal" },
                { id: "sciences-020-c", label: "Le coulomb" },
                { id: "sciences-020-d", label: "Le volt" },
            ],
            correctOptionId: "sciences-020-b",
            explanation: "Le pascal correspond à une force d’un newton répartie sur une surface d’un mètre carré.",
        },
        {
            id: "sciences-021",
            prompt: "Quelle est l’unité de l’intensité du courant électrique dans le Système international ?",
            options: [
                { id: "sciences-021-a", label: "L’ohm" },
                { id: "sciences-021-b", label: "Le farad" },
                { id: "sciences-021-c", label: "Le volt" },
                { id: "sciences-021-d", label: "L’ampère" },
            ],
            correctOptionId: "sciences-021-d",
            explanation: "L’ampère mesure le débit de charge électrique traversant une section de conducteur.",
        },
        {
            id: "sciences-022",
            prompt: "Quelle est l’unité de mesure de la résistance électrique ?",
            options: [
                { id: "sciences-022-a", label: "Le volt" },
                { id: "sciences-022-b", label: "L’ampère" },
                { id: "sciences-022-c", label: "Le watt" },
                { id: "sciences-022-d", label: "L’ohm" },
            ],
            correctOptionId: "sciences-022-d",
            explanation: "L’ohm, de symbole Ω, mesure l’opposition d’un composant au passage du courant électrique.",
        },
        {
            id: "sciences-023",
            prompt: "Que se passe-t-il lorsque deux pôles magnétiques nord sont rapprochés ?",
            options: [
                { id: "sciences-023-a", label: "Ils échangent leurs pôles" },
                { id: "sciences-023-b", label: "Ils se repoussent" },
                { id: "sciences-023-c", label: "Ils deviennent neutres" },
                { id: "sciences-023-d", label: "Ils s’attirent" },
            ],
            correctOptionId: "sciences-023-b",
            explanation: "Deux pôles magnétiques de même nature se repoussent, tandis que des pôles opposés s’attirent.",
        },
        {
            id: "sciences-024",
            prompt: "Quel phénomène permet à un alternateur de produire un courant électrique à partir d’un mouvement mécanique ?",
            options: [
                { id: "sciences-024-a", label: "La réfraction" },
                { id: "sciences-024-b", label: "La conduction thermique" },
                { id: "sciences-024-c", label: "L’induction électromagnétique" },
                { id: "sciences-024-d", label: "La radioactivité" },
            ],
            correctOptionId: "sciences-024-c",
            explanation: "Une variation de flux magnétique à travers un circuit induit une tension électrique, principe mis en évidence par Michael Faraday.",
        },
        {
            id: "sciences-025",
            prompt: "Quelle est approximativement la vitesse de la lumière dans le vide ?",
            options: [
                { id: "sciences-025-a", label: "30 000 km/s" },
                { id: "sciences-025-b", label: "300 000 km/s" },
                { id: "sciences-025-c", label: "3 000 000 km/s" },
                { id: "sciences-025-d", label: "3 000 km/s" },
            ],
            correctOptionId: "sciences-025-b",
            explanation: "La lumière se propage dans le vide à environ 299 792 kilomètres par seconde, souvent arrondis à 300 000 km/s.",
        },
        {
            id: "sciences-026",
            prompt: "Dans le spectre visible, quelle couleur correspond aux longueurs d’onde les plus courtes ?",
            options: [
                { id: "sciences-026-a", label: "Le vert" },
                { id: "sciences-026-b", label: "Le violet" },
                { id: "sciences-026-c", label: "L’orange" },
                { id: "sciences-026-d", label: "Le rouge" },
            ],
            correctOptionId: "sciences-026-b",
            explanation: "Le violet se situe vers l’extrémité des courtes longueurs d’onde du spectre visible, à l’opposé du rouge.",
        },
        {
            id: "sciences-027",
            prompt: "Comment agit une lentille convergente sur des rayons lumineux parallèles à son axe principal ?",
            options: [
                { id: "sciences-027-a", label: "Elle les sépare sans limite" },
                { id: "sciences-027-b", label: "Elle les rassemble vers un foyer" },
                { id: "sciences-027-c", label: "Elle les rend tous perpendiculaires" },
                { id: "sciences-027-d", label: "Elle les absorbe totalement" },
            ],
            correctOptionId: "sciences-027-b",
            explanation: "Après traversée d’une lentille convergente idéale, des rayons parallèles à l’axe se rencontrent au foyer image.",
        },
        {
            id: "sciences-028",
            prompt: "À quelle température correspond le zéro absolu ?",
            options: [
                { id: "sciences-028-a", label: "0 °C" },
                { id: "sciences-028-b", label: "−100 °C" },
                { id: "sciences-028-c", label: "−459,67 °C" },
                { id: "sciences-028-d", label: "−273,15 °C" },
            ],
            correctOptionId: "sciences-028-d",
            explanation: "Le zéro absolu vaut 0 kelvin, soit −273,15 °C ; −459,67 est la valeur correspondante en degrés Fahrenheit.",
        },
        {
            id: "sciences-029",
            prompt: "Quel mode de transfert thermique peut se produire dans le vide ?",
            options: [
                { id: "sciences-029-a", label: "La conduction" },
                { id: "sciences-029-b", label: "L’advection matérielle" },
                { id: "sciences-029-c", label: "La convection" },
                { id: "sciences-029-d", label: "Le rayonnement" },
            ],
            correctOptionId: "sciences-029-d",
            explanation: "Le rayonnement transporte de l’énergie par ondes électromagnétiques et ne nécessite donc pas de milieu matériel.",
        },
        {
            id: "sciences-030",
            prompt: "Quelle est la formule chimique de l’eau ?",
            options: [
                { id: "sciences-030-a", label: "CO₂" },
                { id: "sciences-030-b", label: "H₂O" },
                { id: "sciences-030-c", label: "O₂" },
                { id: "sciences-030-d", label: "NaCl" },
            ],
            correctOptionId: "sciences-030-b",
            explanation: "Une molécule d’eau contient deux atomes d’hydrogène liés à un atome d’oxygène.",
        },
        {
            id: "sciences-031",
            prompt: "À 25 °C, quel pH caractérise une solution aqueuse neutre ?",
            options: [
                { id: "sciences-031-a", label: "7" },
                { id: "sciences-031-b", label: "14" },
                { id: "sciences-031-c", label: "5" },
                { id: "sciences-031-d", label: "0" },
            ],
            correctOptionId: "sciences-031-a",
            explanation: "À 25 °C, une solution neutre contient autant d’ions hydronium que d’ions hydroxyde et possède un pH égal à 7.",
        },
        {
            id: "sciences-032",
            prompt: "Que représente le numéro atomique d’un élément chimique ?",
            options: [
                { id: "sciences-032-a", label: "Le nombre total de nucléons" },
                { id: "sciences-032-b", label: "Le nombre de protons dans son noyau" },
                { id: "sciences-032-c", label: "La masse de l’atome en grammes" },
                { id: "sciences-032-d", label: "Le nombre de couches électroniques" },
            ],
            correctOptionId: "sciences-032-b",
            explanation: "Le nombre de protons définit l’identité de l’élément ; un atome neutre possède aussi autant d’électrons que de protons.",
        },
        {
            id: "sciences-033",
            prompt: "Quel est l’élément chimique le plus abondant dans l’Univers observable ?",
            options: [
                { id: "sciences-033-a", label: "Le carbone" },
                { id: "sciences-033-b", label: "L’hydrogène" },
                { id: "sciences-033-c", label: "L’hélium" },
                { id: "sciences-033-d", label: "L’oxygène" },
            ],
            correctOptionId: "sciences-033-b",
            explanation: "L’hydrogène représente la majorité des atomes de l’Univers et constitue le principal combustible des étoiles.",
        },
        {
            id: "sciences-034",
            prompt: "Quel élément chimique a pour symbole Fe ?",
            options: [
                { id: "sciences-034-a", label: "Le francium" },
                { id: "sciences-034-b", label: "Le fluor" },
                { id: "sciences-034-c", label: "Le fer" },
                { id: "sciences-034-d", label: "Le fermium" },
            ],
            correctOptionId: "sciences-034-c",
            explanation: "Le symbole Fe vient du latin ferrum et désigne le fer, élément de numéro atomique 26.",
        },
        {
            id: "sciences-035",
            prompt: "Qu’est-ce qui caractérise principalement une liaison covalente ?",
            options: [
                { id: "sciences-035-a", label: "Le partage d’une ou plusieurs paires d’électrons" },
                { id: "sciences-035-b", label: "L’absence totale d’interaction électronique" },
                { id: "sciences-035-c", label: "La fusion de deux noyaux" },
                { id: "sciences-035-d", label: "Le transfert obligatoire de neutrons" },
            ],
            correctOptionId: "sciences-035-a",
            explanation: "Dans une liaison covalente, des atomes stabilisent leur structure électronique en partageant des électrons.",
        },
        {
            id: "sciences-036",
            prompt: "Quel est l’effet d’un catalyseur sur une réaction chimique ?",
            options: [
                { id: "sciences-036-a", label: "Il augmente toujours la température du milieu" },
                {
                    id: "sciences-036-b",
                    label: "Il change la quantité finale imposée par l’équilibre",
                },
                {
                    id: "sciences-036-c",
                    label: "Il abaisse l’énergie d’activation sans être consommé globalement",
                },
                { id: "sciences-036-d", label: "Il transforme les produits en nouveaux éléments" },
            ],
            correctOptionId: "sciences-036-c",
            explanation: "Un catalyseur offre un chemin réactionnel plus accessible et accélère la réaction sans modifier le bilan global de l’équilibre.",
        },
        {
            id: "sciences-037",
            prompt: "Dans une réaction d’oxydoréduction, que signifie l’oxydation d’une espèce chimique ?",
            options: [
                { id: "sciences-037-a", label: "Un gain obligatoire de neutrons" },
                { id: "sciences-037-b", label: "Une diminution systématique de température" },
                { id: "sciences-037-c", label: "Un gain d’électrons" },
                { id: "sciences-037-d", label: "Une perte d’électrons" },
            ],
            correctOptionId: "sciences-037-d",
            explanation: "L’oxydation correspond à une perte d’électrons, tandis que la réduction correspond à un gain d’électrons.",
        },
        {
            id: "sciences-038",
            prompt: "Quel élément Marie et Pierre Curie ont-ils nommé en référence à la Pologne ?",
            options: [
                { id: "sciences-038-a", label: "Le francium" },
                { id: "sciences-038-b", label: "Le polonium" },
                { id: "sciences-038-c", label: "Le radon" },
                { id: "sciences-038-d", label: "Le curium" },
            ],
            correctOptionId: "sciences-038-b",
            explanation: "Marie Curie a choisi le nom polonium en hommage à son pays natal, la Pologne, alors privée d’indépendance.",
        },
        {
            id: "sciences-039",
            prompt: "Quelle planète est la plus proche du Soleil ?",
            options: [
                { id: "sciences-039-a", label: "Mercure" },
                { id: "sciences-039-b", label: "Vénus" },
                { id: "sciences-039-c", label: "La Terre" },
                { id: "sciences-039-d", label: "Mars" },
            ],
            correctOptionId: "sciences-039-a",
            explanation: "Mercure est la planète dont l’orbite est la plus proche du Soleil, avec une distance moyenne d’environ 58 millions de kilomètres.",
        },
        {
            id: "sciences-040",
            prompt: "Quelle est la cause principale des saisons sur Terre ?",
            options: [
                { id: "sciences-040-a", label: "L’activité des taches solaires" },
                {
                    id: "sciences-040-b",
                    label: "Les changements de vitesse de rotation de la Terre",
                },
                { id: "sciences-040-c", label: "La variation mensuelle de la distance Terre-Lune" },
                {
                    id: "sciences-040-d",
                    label: "L’inclinaison de l’axe terrestre pendant sa révolution autour du Soleil",
                },
            ],
            correctOptionId: "sciences-040-d",
            explanation: "L’axe terrestre incliné modifie au cours de l’année l’angle des rayons solaires et la durée du jour dans chaque hémisphère.",
        },
        {
            id: "sciences-041",
            prompt: "Quel est le satellite naturel de la Terre ?",
            options: [
                { id: "sciences-041-a", label: "La Lune" },
                { id: "sciences-041-b", label: "Mars" },
                { id: "sciences-041-c", label: "Vénus" },
                { id: "sciences-041-d", label: "Titan" },
            ],
            correctOptionId: "sciences-041-a",
            explanation: "La Lune est l’unique satellite naturel permanent de la Terre et gravite autour de notre planète.",
        },
        {
            id: "sciences-042",
            prompt: "Pourquoi la Lune présente-t-elle différentes phases vues depuis la Terre ?",
            options: [
                {
                    id: "sciences-042-a",
                    label: "Des nuages lunaires masquent progressivement sa surface",
                },
                { id: "sciences-042-b", label: "L’ombre de la Terre recouvre la Lune chaque mois" },
                { id: "sciences-042-c", label: "La Lune produit une quantité variable de lumière" },
                {
                    id: "sciences-042-d",
                    label: "La portion éclairée visible change selon la position relative du Soleil, de la Terre et de la Lune",
                },
            ],
            correctOptionId: "sciences-042-d",
            explanation: "La moitié de la Lune éclairée par le Soleil reste constante, mais la fraction visible depuis la Terre varie au cours de son orbite.",
        },
        {
            id: "sciences-043",
            prompt: "Quelle réaction fournit l’essentiel de l’énergie rayonnée par le Soleil ?",
            options: [
                { id: "sciences-043-a", label: "La combustion chimique de carbone" },
                { id: "sciences-043-b", label: "La désintégration du fer" },
                { id: "sciences-043-c", label: "La fusion de noyaux d’hydrogène en hélium" },
                { id: "sciences-043-d", label: "La fission de noyaux d’uranium" },
            ],
            correctOptionId: "sciences-043-c",
            explanation: "Dans le cœur du Soleil, la fusion transforme principalement l’hydrogène en hélium et libère de l’énergie.",
        },
        {
            id: "sciences-044",
            prompt: "À quel grand type appartient la Voie lactée ?",
            options: [
                { id: "sciences-044-a", label: "Une galaxie elliptique géante" },
                { id: "sciences-044-b", label: "Une galaxie spirale barrée" },
                { id: "sciences-044-c", label: "Une galaxie annulaire parfaite" },
                { id: "sciences-044-d", label: "Une galaxie irrégulière sans structure" },
            ],
            correctOptionId: "sciences-044-b",
            explanation: "La Voie lactée possède des bras spiraux et une barre centrale d’étoiles, ce qui la classe parmi les galaxies spirales barrées.",
        },
        {
            id: "sciences-045",
            prompt: "Quelle observation constitue un indice majeur de l’expansion de l’Univers ?",
            options: [
                { id: "sciences-045-a", label: "Les éclipses solaires" },
                { id: "sciences-045-b", label: "La couleur bleue des océans" },
                {
                    id: "sciences-045-c",
                    label: "Le décalage vers le rouge de la lumière des galaxies lointaines",
                },
                { id: "sciences-045-d", label: "La précession de l’axe terrestre" },
            ],
            correctOptionId: "sciences-045-c",
            explanation: "En moyenne, plus une galaxie est lointaine, plus son spectre est décalé vers le rouge, signe que l’espace entre les galaxies s’étend.",
        },
        {
            id: "sciences-046",
            prompt: "Quel type de roche se forme par refroidissement et solidification d’un magma ou d’une lave ?",
            options: [
                { id: "sciences-046-a", label: "Une roche magmatique" },
                { id: "sciences-046-b", label: "Une roche sédimentaire" },
                { id: "sciences-046-c", label: "Une roche exclusivement métamorphique" },
                { id: "sciences-046-d", label: "Une roche organique" },
            ],
            correctOptionId: "sciences-046-a",
            explanation: "Les roches magmatiques, comme le granite ou le basalte, proviennent de la cristallisation d’un matériau fondu.",
        },
        {
            id: "sciences-047",
            prompt: "Où se produisent la plupart des séismes tectoniques ?",
            options: [
                { id: "sciences-047-a", label: "Le long des limites de plaques lithosphériques" },
                { id: "sciences-047-b", label: "Sous les calottes glaciaires seulement" },
                { id: "sciences-047-c", label: "Uniquement au centre des continents" },
                { id: "sciences-047-d", label: "Dans la haute atmosphère" },
            ],
            correctOptionId: "sciences-047-a",
            explanation: "Les mouvements relatifs des plaques accumulent puis libèrent des contraintes, surtout au voisinage de leurs limites.",
        },
        {
            id: "sciences-048",
            prompt: "Dans quelle couche de l’atmosphère se produisent la plupart des phénomènes météorologiques ?",
            options: [
                { id: "sciences-048-a", label: "La stratosphère" },
                { id: "sciences-048-b", label: "La thermosphère" },
                { id: "sciences-048-c", label: "La mésosphère" },
                { id: "sciences-048-d", label: "La troposphère" },
            ],
            correctOptionId: "sciences-048-d",
            explanation: "La troposphère contient la majorité de la vapeur d’eau atmosphérique et accueille l’essentiel des nuages et des précipitations.",
        },
        {
            id: "sciences-049",
            prompt: "Quel gaz est le plus abondant dans l’atmosphère terrestre sèche ?",
            options: [
                { id: "sciences-049-a", label: "Le dioxygène" },
                { id: "sciences-049-b", label: "Le diazote" },
                { id: "sciences-049-c", label: "Le dioxyde de carbone" },
                { id: "sciences-049-d", label: "L’hydrogène" },
            ],
            correctOptionId: "sciences-049-b",
            explanation: "Le diazote représente environ 78 % de l’atmosphère sèche, contre environ 21 % pour le dioxygène.",
        },
        {
            id: "sciences-050",
            prompt: "À quel scientifique attribue-t-on la découverte de la pénicilline en 1928 ?",
            options: [
                { id: "sciences-050-a", label: "Gregor Mendel" },
                { id: "sciences-050-b", label: "Louis Pasteur" },
                { id: "sciences-050-c", label: "Robert Koch" },
                { id: "sciences-050-d", label: "Alexander Fleming" },
            ],
            correctOptionId: "sciences-050-d",
            explanation: "Alexander Fleming observa qu’une moisissure du genre Penicillium empêchait la croissance de bactéries, ouvrant la voie aux antibiotiques.",
        },
    ],
};
